### ISSUE TITLE
Software: Text postprocessing

### ISSUE THREAD

**Issue by korrawat** [pkarnati2004/ppat-project#18]
In the WHOLE HEART's menu example, the order of the texts being read is different from the order we'd normally read.

![20181023-8](https://user-images.githubusercontent.com/23010630/47620763-5a67d700-dac4-11e8-8ece-717e57d76e09.jpg)

Now we naively read the responses from Google OCR's in this [method](https://github.com/pkarnati2004/ppat-project/blob/master/raspberry-pi/google_vision.py#L46-L56). The `words.split('\n')` is a list including:

```
SIGNATURE BOWLS
CASSIE
MISO
TAZON
STREET FO0DS
SEOUL
KAYA
HISHITO PEPPERS
STREET CORN
FALAFELDOG
LEVANT
SEETA
1 VIET
MISSION
CLD BAY BRUSSELS
WHOLE HEART
phovisiond
```

## Ideas for improvement
- Use x, y coordinates of each word and compare them to find a reasonable order. (We need to first find out how Google sort them.)
- When there's a typo, e.g. "STREET FO0DS", maybe we can check a dictionary and try to correct it?

This depends on #1 though. After we change to an offline library, the problems may change.

**Comment by pkarnati2004** [comment]
@autocorrect.py
