### ISSUE TITLE
Software: get better text-to-speech conversion

### ISSUE THREAD

**Issue by pkarnati2004** [pkarnati2004/ppat-project#3]
James lowered the speed of the text-to-speech.

**Comment by korrawat** [comment]
Speed issue should be fixed by [this commit](https://github.com/pkarnati2004/ppat-project/commit/cba0ff9fe249b061f651047a28defb661e40cfe3).

Maybe more testing?

Anything else we want to improve? (e.g. clarity?) but if we stick to `pyttsx` then we probably can't improve it too much

**Comment by korrawat** [comment]
Voice quality is still a problem

**Comment by korrawat** [comment]
@Cattalyya solved this with pico2wave and aplay
