### ISSUE TITLE
Hardware: raspberry pi fix audio

### ISSUE THREAD

**Issue by pkarnati2004** [pkarnati2004/ppat-project#4]

**Comment by korrawat** [comment]
Wait for a new tiny speaker and test this.

**Comment by korrawat** [comment]
On Oct 22 while trying to make sound output via usb not HDMI, I edited some config file but I can't remember which one exactly.

Maybe `/usr/share/alsa/alsa.conf` according to [this](https://learn.adafruit.com/usb-audio-cards-with-a-raspberry-pi?view=all#raspbian-stretch-updating-alsa-options-7-1)

(or `/etc/asound.conf`?) I'm not sure if it's actually effective and I no longer remember the exact details.

or according to [this](https://computers.tutsplus.com/articles/using-a-usb-audio-device-with-a-raspberry-pi--mac-55876)?

**Comment by korrawat** [comment]
`sudo alsactl store`

ref:
- https://askubuntu.com/questions/50067/howto-save-alsamixer-settings
- https://unix.stackexchange.com/questions/210113/default-sound-volume-for-all-alsa-devices

**Comment by korrawat** [comment]
http://blog.scphillips.com/posts/2013/01/sound-configuration-on-raspberry-pi-with-alsa/

**Comment by korrawat** [comment]
https://community.blokas.io/t/play-samples-with-aplay/215/2

Changing `~/.asoundrc` into the following fixes the aplay issue! 
```
pcm.!default {
        type plug
        slave.pcm "qhw"
}

pcm.qhw {
        type hw
        card 1
}

ctl.!default {
        type hw
        card 1
}
```
The issue was `aplay: set_params:1305: Channels count non available`.
