### ISSUE TITLE
Other: CAD files for glasses (obtain + modify)

### ISSUE THREAD

**Issue by pkarnati2004** [pkarnati2004/ppat-project#5]
Romeo found CAD files from [GrabCAD](https://grabcad.com/library/oculos-de-sol-ray-ban-sergio-ray-ban-sergio-sunglasses-1). You can create a free student account and open it on [Onshape](https://www.onshape.com/).

**Comment by romflores95** [comment]
[Glasses](https://grabcad.com/library/oculos-de-sol-ray-ban-sergio-ray-ban-sergio-sunglasses-1
)
I opened these with OnShape.

**Comment by pkarnati2004** [comment]
Not needed
